<?php
return [
    'Стандартные контейнеры также называются универсальными контейнерами.'=>'Standardbehälter werden auch Universalbehälter genannt.',
    'Рефрежираторная установка размещена таким образом, чтобы внешние размеры контейнера соответствовали стандартам ISO и установка оптимально помещалась вовнутрь. Наличие рефрижераторной установки приводит к уменьшению внутреннего объема и подвижной нагрузки.'=>'Die Kälteanlage ist so platziert, dass die Außenmaße des Containers den ISO-Normen entsprechen und die Installation optimal platziert ist.',
    'Контейнер имеет отличительную структуру. Крыша состоит из передвижных рам и тента. Дверная перемычка может быть вращающейся.'=>'The container has a distinctive structure. The roof consists of movable frames and awning. The door jumper can be rotating.',
    'Погрузочный поддон состоит из напольного перекрытия с высокой несущей способностью и стального каркаса с настилом из мягкой древесины и двух перегородок'=>'Die Ladepalette besteht aus einem Bodenbelag mit hoher Tragfähigkeit und einem Stahlrahmen mit Weichholzboden und zwei Trennwänden',
    'Такие контейнеры должны быть загружены не менее чем на 80 процентов для предотвращения колебания жидкого груза. С другой стороны, контейнеры не должны заполняться больше чем на 95 процентов, в противном случае возникнет нехватка свободного пространства'=>'Solche Container sollten mindestens 80 Prozent beladen werden, um Schwankungen in flüssiger Ladung zu vermeiden. Auf der anderen Seite sollten Container nicht mehr als 95 Prozent gefüllt werden, sonst gibt es einen Mangel an freiem Platz',
    'Погрузочные поддоны закрыты со всех сторон. Отличия между видами контейнеров:'=>'Das Laden von Paletten ist allseitig geschlossen. Unterschiede zwischen Containertypen:',
    ' • Стандартные контейнеры с дверцами с одной или обеих сторон'=>' • Standardbehälter mit ein- oder beidseitigen Türen',
    ' • Стандартные контейнеры с дверцами на одной или обеих сторонах и дверцами по всей длине'=>' • Standardbehälter mit Türen auf einer oder beiden Seiten und Türen über die gesamte Länge',
    ' • Стандартные контейнеры с дверцами на одной или обеих сторонах'=>' • Standardbehälter mit ein- oder beidseitigen Türen',
    'Стандартные контейнеры также отличаются между собой в зависимости от размеров, массы'=>'Standardbehälter unterscheiden sich je nach Größe, Gewicht auch untereinander',
    'Как правило используются 20 и 40 футовые контейнеры. Контейнеры меньших размеров используются в редких случаях. Часто используются контейнеры даже больших размеров, например, 45 футов.'=>'In der Regel werden 20 und 40 Fuß Container verwendet. Kleinere Behälter werden in seltenen Fällen verwendet. Oft gebrauchte Container sind noch größer, zum Beispiel 45 Fuß.',
    'Рефрежираторная установка размещена таким образом, чтобы внешние размеры контейнера соответствовали стандартам ISO и установка оптимально помещалась во внутрь. Наличие рефрижераторной установки приводит к уменьшению внутреннего объема и подвижной нагрузки.'=>'Die Kälteanlage ist so platziert, dass die Außenmaße des Containers den ISO-Normen entsprechen und die Installation optimal platziert ist. Das Vorhandensein einer Kühlschrankinstallation führt zu einer Verringerung des Innenvolumens und der mobilen Last.',
    'на борту судна груз должен быть подключен к системе электропитания. количество перевозимых рефрижераторных контейнеров зависит от мощности системы электропитания судна. при слабой мощности, могут использоваться силовые агрегаты, которые устанавливаются радом с дизельными генераторами согласно требованиям ISO по размещению 20 футовых контейнеров. на терминале контейнеры подключают к системе электропитания терминала. при транспортировке автомобильным или железнодорожным транспортом, рефрижераторные блоки работают от электрогенераторов, которые в свою очередь могут быть подключены к холодильной установке.'=>'An Bord muss die Ladung an das Stromnetz angeschlossen werden. Die Anzahl der beförderten Kühlcontainer hängt von der Kapazität des Schiffsnetzes ab. Bei geringer Leistung können Leistungseinheiten verwendet werden, die in der Nähe von Dieselgeneratoren in Übereinstimmung mit den ISO-Anforderungen für die Platzierung von 20-Fuß-Containern installiert sind. Am Terminal sind die Container mit dem Terminalnetz verbunden. Bei der Beförderung auf der Straße oder Schiene arbeiten die Kühlanlagen von elektrischen Generatoren, die wiederum an eine Kälteanlage angeschlossen werden können.',
    'Поток воздуха через контейнер с нижней и верхней частей; теплый воздух поднимается изнутри контейнера, охлаждается в рефрижераторной установке и затем обратно вдувается в контейнер в уже охложденном виде.'=>'Luftströmung durch den Behälter von den unteren und oberen Teilen; Warmluft steigt aus dem Behälter, kühlt in einem Kühlschrank und wird dann wieder in den Behälter in einer bereits gekühlten Form geblasen.',
    'Для обеспечения правильной циркуляции охложденного воздуха, на напольном перекрытии встроена решетка. Поддоны образуют дополнительное пространство между напольным пекрытием и грузом, что обеспечивает продув. Кроме того, боковые стенки контейнера гофрированы, что обспечивает необходимый поток воздуха.'=>'Um eine ordnungsgemäße Zirkulation von gekühlter Luft zu gewährleisten, ist ein Bodengrill in den Boden eingebaut. Die Paletten bilden einen zusätzlichen Raum zwischen der Bodenüberlappung und der Last, was ein Blasen sicherstellt. Darüber hinaus sind die Seitenwände des Behälters gewellt, was den notwendigen Luftstrom aufdringt.',
    'В верхней части контейнера, должно оставаться пространство (не менее 12 см) для продува. Поэтому, при упаковке контейнера, над грузом необходимо оставить свободное пространство. Максимальная высота загрузки отмечена на боковых стенках.'=>'An der Oberseite des Behälters muss ein Platz (mindestens 12 cm) zum Blasen vorhanden sein. Wenn Sie also den Behälter verpacken, lassen Sie den Raum über die Ladung. Die maximale Ladehöhe ist an den Seitenwänden markiert.',
    'Для обеспечения вертикального потока воздуха снизу вверх, конструкция упаковки должна быть соответствующая, и груз размещен правильно'=>'Um eine vertikale Luftströmung von unten nach oben zu gewährleisten, muss das Verpackungsdesign angemessen sein und die Last korrekt platzieren',
    'Регулирование температуры, и наличие интегрального блока, также позволяют контролировать поступление свежего воздуха, например, для выведения метаболических продуктов, таких как СО2 и этилена при перевозке фруктов.'=>'Die Temperaturregelung und das Vorhandensein einer integrierten Einheit erlauben es Ihnen auch, die Aufnahme von Frischluft zu überwachen, zum Beispiel für die Entfernung von Stoffwechselprodukten wie CO2 und Ethylen beim Transport von Früchten.',
    'в холодильных установках измеряется температура поступающего и отработанного воздуха, и в зависимости от рабочего режима данные температуры изпользуются для регулирования потока холодного воздуха. температуру можно измерить разными способами. устройство записи Partlow фиксирует температуру отработанного воздуха, тем самым определяется температурный режим для груза. устройство регистрации данных определяет уровень температуры цифровым способом и выводит данные на дисплей. после передачи данных на компьютер, информация подвергается анализу.'=>'Die Temperatur der ankommenden und abgehenden Luft wird in Kälteanlagen gemessen und in Abhängigkeit von der Betriebsart werden diese Temperaturen zur Steuerung der Kaltluftströmung verwendet. Die Temperatur kann in vielerlei Hinsicht gemessen werden. Das Partlow-Aufzeichnungsgerät zeichnet die Temperatur der Abluft auf und bestimmt so die Temperaturregelung für die Last. Der Datenlogger erkennt das Temperaturniveau digital und zeigt die Daten auf dem Display an. Nach der Datenübertragung an den Computer wird die Information analysiert.',
    'Температурный датчик прикреплен с наружной стороны рефрижераторной установки для контроля за работой установки.'=>'Der Temperatursensor wird von der Außenseite des Kühlschranks angeschlossen, um den Betrieb der Anlage zu steuern.',
    'Устройства для записи аналоговых и цифровых данных также могут быть размещены непосредственно на грузе для измерения температуры внутри контейнера. Устройсво записи должно быть уставновлено таким образом, чтобы фиксировать критические температуры (внутри упаковки).'=>'Geräte zur Aufnahme von analogen und digitalen Daten können auch direkt auf die Ladung platziert werden, um die Temperatur im Inneren des Containers zu messen. Das Aufzeichnungsgerät muss so eingestellt werden, dass die kritischen Temperaturen (innerhalb des Gehäuses) fixiert werden.',
    'Встроенные блоки могут быть размещены на верхней и нижней палубах судна. Размещение на верхней палубе имеет свои преимущества, т.к. тепло от воздуха может легко рассеиваться. Однако контейнеры подвержены солнечной радиации, что требует высокой хладопроизводительности холодильных установок.'=>'Eingebaute Einheiten können auf den oberen und unteren Decks des Schiffes platziert werden. Unterkunft auf dem Oberdeck hat seine Vorteile, denn Wärme aus der Luft kann leicht zerstreuen. Allerdings sind Container einer Sonneneinstrahlung ausgesetzt, die eine hohe Kühlleistung von Kälteanlagen erfordert.',
    'Показатели'=>'Indikatoren',
    'Использование'=>'Verwenden',
    'контейнер-рефрижератор используется для перевозки груза, требующего наличия одинаковой температуры как верхней так и нижней точек замерзания. К такому грузу относятся охлаждённые и замороженные продукты, требующие определенной температуры. Это могут быть фрукты, овощи, мясные и молочные продукты, масло и сыр.'=>'Der gekühlte Behälter wird verwendet, um Fracht zu transportieren, die die gleiche Temperatur sowohl der oberen als auch der unteren Gefrierpunkte erfordert. Diese Ladung umfasst gekühlte und gefrorene Lebensmittel, die eine bestimmte Temperatur erfordern. Es können Früchte, Gemüse, Fleisch und Milchprodukte, Butter und Käse sein.',
    'Агрегаты с большими объемами используются для объемных и легких грузов (фрукты, цветы)'=>'Aggregate mit großen Volumina werden für Schüttgut und leichte Lasten (Früchte, Blüten)',
    'На сегодняшний день, грузы, требующие заморозки, перевозятся во встроенных агрегатах, которые намного лучше, чем контейнеры с вентиляционными отверстиями.'=>'Bisher werden Lasten, die einfrieren müssen, in eingebauten Einheiten transportiert, die viel besser sind als Behälter mit Belüftungslöchern.',
    'Мясо иногда перевозят в подвешенном состоянии, для этого потолки в контейнерах оборудованы специальными передвижными крюками.'=>'Fleisch wird in einem aufgehängten Zustand transportiert, zu diesem Zweck sind die Decken in Behältern mit speziellen mobilen Haken ausgestattet.',
    'Стенки контейнера сделаны из гофрированной стали. Настил деревянный.'=>'Die Wände des Behälters sind aus Wellblech gefertigt. Holzboden.',
    'Контейнер имеет отличительную структуру. Крыша состоит из передвижных рам и тента. Дверная перемычка может быть вращающейся.'=>'Der Container hat eine unverwechselbare Struktur. Das Dach besteht aus beweglichen Rahmen und Markise. Die Türbrücke kann sich drehen.',
    'Эти две особенности значительно упрощают процесс упаковки и распаковки контейнера. В частности, очень легко упаковать и распаковать контейнер сверху или через двери пр попомщи подъемника или домкрата, если открыта крыша и повернута дверная перемычка'=>'Diese beiden Merkmale kontrollieren den Prozess der Verpackung und des Auspackens des Behälters. Insbesondere ist es sehr einfach, den Behälter von oben oder durch die Türen auszupacken und auszupacken, pripamisch heben oder stecken, wenn man das Dach öffnet und die Türbrücke dreht',
    'Необходимо отметить, что опора крыши в открытом контейнере предназначена для поддержания тента и обеспечить устойчивость контейнера. погрузочный поддон в этом случае наиболее подходящее средство для высоких грузов.'=>'Es ist zu beachten, dass die Dachstütze im offenen Behälter zur Unterstützung des Zeltes und zur Stabilität des Behälters ausgelegt ist. Die Ladepalette ist in diesem Fall das geeignetste Mittel für hohe Belastungen.',
    'Крепежные кольца установлены на верхней и нижней боковых балках и угловых опорах. Кольца могут выдержать груз до 1000 кг.'=>'Befestigungsringe sind auf den oberen und unteren Seitenbalken und Eckstützen montiert. Ringe können Belastungen bis zu 1000 kg widerstehen.',
    'Стандартные размеры контейнера с открытым верхом 20 и 40 футов.'=>'Standard-Containergrößen mit offener Oberseite 20 und 40 Fuß.',
    'Контейнеры с открытым верхом используются для всех видов генеральных грузов (сухой груз). Назначение:'=>'Container mit offener Oberseite werden für alle Arten von Stückgut (Trockenfracht) verwendet. Zweck:',
    ' • упаковка и распаковка сверху или через двери при помощи крана или домкрата'=>' • Packen und Auspacken von oben oder durch die Türen mit einem Kran oder einem Wagenheber',
    ' • для высоких грузов'=>' • für hohe Belastungen',
    'Погрузочный поддон состоит из напольного перекрытия с высокой несущей способностью и стального каркаса с настилом из мягкой древесины и двух перегородок; поддон может быть закрепленный или разборной. Перегородки защищают груз, при этом несколько поддонов крепятся один на другой. Размеры погрузочного поддона 20 и 40 футов.'=>'Die Ladepalette besteht aus einem Bodenbelag mit hoher Tragfähigkeit und einem Stahlrahmen mit einem Deck aus Weichholz und zwei Trennwänden; Die Palette kann fixiert oder zusammenklappbar sein. Trennwände schützen die Last, wobei mehrere Paletten aneinander befestigt sind. Die Abmessungen der Ladepalette betragen 20 und 40 Fuß.',
    'Крепежные кольца, к которым крепится груз, устанавливаются на боковых балках, угловых опорах и полу. Кольца могут выдержать нагрузку до 2000 кг, в случае с 20 футовыми погрузочными поддонами или до 4000 кг с 40 футовыми поддонами.'=>'Befestigungsringe, an denen die Last befestigt ist, sind auf Seitenbalken, Eckstützen und Boden montiert. Ringe können Belastungen von bis zu 2.000 kg widerstehen, bei 20-Fuß-Paletten oder bis zu 4.000 kg mit 40-Fuß-Paletten.',
    'У некоторых видов 20 футовых контейнеров имеются отверстия для вилочныых погрузчиков.'=>'Einige Arten von 20-Fuß-Containern haben Löcher für Gabelstapler.',
    '40 футовые поддоны имеют входы s- образной формы с каждой стороны. Иногда на них крепятся крепежная лебедка с 2 тонными крепежными канатами.'=>'40 Fußpaletten haben s-förmige Eingänge auf jeder Seite. Manchmal ist eine Befestigungswinde mit 2 Tonnen Befestigungsseilen an ihnen befestigt.',
    'для перевозки отдельных видов грузов, погрузочные поддоны могут быть оснащены подпорами.'=>'Für den Transport von bestimmten Frachttypen können Ladungspaletten mit Stützen ausgerüstet werden.',
    'Поддоны используются для перевозки тяжелых и крупногабатиных грузов.'=>'Paletten werden für den Transport von schweren und großvolumigen Fracht verwendet.',
    'Такие контейнеры должны быть загружены не менее чем на 80 процентов для предотвращения колебания жидкого груза. С другой стороны, контейнеры не должны заполняться больше чем на 95 процентов, в противном случае возникнет нехватка свободного пространства, необходимого для термального расширения, которое может быть рассчитано для каждого груза по формуле:'=>'Solche Container sollten mindestens 80 Prozent beladen werden, um Schwankungen in flüssiger Ladung zu vermeiden. Auf der anderen Seite sollten die Container nicht mehr als 95 Prozent gefüllt werden, sonst wird es einen Mangel an freiem Platzbedarf für die thermische Ausdehnung geben, der für jede Ladung nach der Formel berechnet werden kann:',
    'изменение объема'=>'Volumenänderung',
    'объем при начальной температуре'=>'Volumen bei Anfangstemperatur',
    'окончательный объем при температуре'=>'das Endvolumen bei der Temperatur',
    'коэффициент термального расширения'=>'Wärmeausdehnungskoeffizient',
    'разница температур в градусах Кельвина'=>'Temperaturunterschied in Grad Kelvin',
    'контейнер для жидких грузов, предназначенный для перевозки пищевых продуктов, должен быть маркирован "только для жидких грузов".'=>'Ein Container für flüssige Ladung, der für den Transport von Lebensmitteln bestimmt ist, ist "nur für flüssige Ladungen" zu kennzeichnen.',
    'Некоторые виды опасных веществ должны перевозиться в контейнерах для жидких грузов с внутренними или внешними отверстиями в нижней части корпуса контейнера.'=>'Einige Arten von gefährlichen Stoffen sollten in flüssigen Frachtcontainern mit Innen- oder Außenlöchern im Boden des Behälterkörpers transportiert werden.',
    'Контейнеры для жидких грузов должны находиться при давлении до 3 бар. испытательное давление составляет 4,5 бар'=>'Container für flüssige Ladung müssen bis zu 3 bar betragen. der Prüfdruck beträgt 4,5 bar',
    'если для перевозки груза требуется транспортное средства с регулировкой температурного режима, контейнеры-цистерны могут быть оснащены системами охлаждения или подогрева. температурный режим для груза может быть точно определен при помощи датчиков температуры'=>'Wenn der Transport von Gütern ein Fahrzeug mit Temperaturregelung erfordert, können Tankcontainer mit Kühl- oder Heizungsanlagen ausgerüstet werden. Die Temperaturregelung für die Last kann mit Temperatursensoren genau bestimmt werden',
    'Контейнеры для жидкостей используются для перевозки жидких грузов, например:'=>'Behälter für Flüssigkeiten werden für den Transport von flüssiger Ladung verwendet, zum Beispiel:',
    ' • пищевые продукты: соки, спирт, оливковое масло'=>' • Lebensmittel: Säfte, Alkohol, Olivenöl',
    ' • химикаты: опасные вещества, топливо, токсичные вещества, вещества для защиты от коррозии'=>' • Chemikalien: Angst vor Substanz, Treibstoff, giftige Stoffe, Korrosionsschutzmittel',

    'организовывает контейнерную перевозку грузов морем в любую точку мира, мы имеем возможность предложить вам выгодные условия доставки и оптимальные для вас маршруты, соединяющие страны и континенты.
                При сотрудничестве с нами вам доступны перевозки из Китая Юго-Восточной Азии, Ближнего Востока, Индии, Африки, Северной Америки, и стран Европы в Россию. Возможна доставка «от двери до двери». Для получения грузов используются прибалтийские и европейские порты и склады.</p>
                <br/>
                <p>Компания SeaLines разрабатывает логистическую цепочку и осуществляет доставку грузов «от двери до двери», начиная с этапа формирования документации и заканчивая выгрузкой контейнера на вашем складе.</p>
                <br/>
                <p>Наша компания предоставляет большой перечень услуг. Став нашим партнером, у Вас появятся возможности, которые другие компании Вам не смогут предоставить. С нашей помощью Вы сможете: доставить свой груз, забыть про оформление документации, про портовые услуги и прочие факторы. Так же, компания SeaLines предлагает своим партнерам приумножить свой капитал. Один из видов деятельности компании заключается в том, что Мы Вам можем предложить взять в субаренду\аренду\аренду с правом выкупа контейнера, для которых уже налажена логистическая цепочка, загрузка его более рентабельным товаром. Вам остается отслеживать онлайн свой контейнер. Также мы предоставляем удобную для клиента опцию выкупа контейнеров (buy-back).</p>
                <br/>
                <p>Мы считаем своей миссией сохранить ваше время, сделать ваш продукт конкурентным и оптимизировать транспортные расходы. Мы помогаем перевезти груз из любой точки мира легко и быстро, без лишних хлопот и затрат.<br/>
                Мы завоевали доверие наших клиентов тем, что предложили оптимальные решения по перевозке грузов и исключили любые ошибки, связанные с человеческим фактором.<br/>
                Контейнерные перевозки морем — лучший, в некоторых случаях даже единственный вариант межконтинентальной доставки грузов. Надежно и экономично.</p>
                <br/>
                <ul>Преимущества перевозок по-морю:<br/>
                    <li> - низкая стоимость доставки морем во многом объясняется возможностью комплектации сборных грузов.</li>
                    <li> - высокая грузоподъемность, в случае с крупногабаритными грузами, перевозка контейнеров морем зачастую становится не только лучшим, но и единственно возможным вариантом доставки.</li>
                    <li> - сохранность груза при транспортировке контейнеров морем практически отсутствуют — риск повреждения грузов минимальный.
                    Sea Lines Company  является заметным игроком на контейнерном рынке в Европе, Балтии, России и СНГ. Мы специализируемся на контейнерах самого широкого спектра типов, габаритов и целевого назначения - сухогрузные или универсальные (морские) контейнеры, рефрижераторные контейнеры (реферы), танк-контейнеры, специализированные контейнеры и т.д. Помимо этого мы поставляем и налаживаем вспомогательное оборудование для контейнеров: генераторные установки (дженсеты) и т.д.</li>
                </ul>
                <br/>
                <p>SeaLines Company работает на контейнерном рынке более 5 лет, и достигнутый за годы работы высокий уровень понимания бизнес-потребностей клиентов помогает быстро и эффективно решать все вопросы, связанные с использованием контейнеров для мультимодальных перевозок и складирования всех видов грузов. Мы обеспечиваем клиентам готовые и индивидуальные решения в транспортировке, логистике, строительстве и любых других видах деятельности, где находится применение контейнерам.</p>
                <br/>
                <p>Уже более 5ти лет SeaLines Company обеспечивает высокую надежность и безопасность контейнерного сервиса для своих клиентов. Мы ручаемся за конфиденциальность и сохранность грузов при перевозке и хранении (в частности, на охраняемой территории, прилегающей к портовой зоне).</p>
                <br/>'=>'organisiert Containertransport von Fracht auf dem Seeweg überall auf der Welt, wir haben die Möglichkeit, Ihnen günstige Lieferzeiten und optimale Routen für Sie anzubieten, die Länder und Kontinente miteinander verbinden.
                In Zusammenarbeit mit uns können Sie Transport von China nach Südostasien, dem Mittleren Osten, Indien, Afrika, Nordamerika und Europa nach Russland. Lieferung möglich "von Tür zu Tür". Um Fracht zu erhalten, werden baltische und europäische Häfen und Lagerhäuser verwendet.</p>
                <br/>
                <p>SeaLines entwickelt eine Logistikkette und liefert die Ware von der Tür zu Tür ab dem Beginn der Dokumentation und endet mit dem Entladen des Containers in Ihrem Lager.</p>
                <br/>
                <p>Unsere Firma bietet eine breite Palette von Dienstleistungen. Als unser Partner werden Sie Chancen haben, die andere Unternehmen nicht in der Lage sein werden, Ihnen zu bieten. Mit unserer Hilfe können Sie: Ihre Ladung liefern, über die Gestaltung der Dokumentation, über Hafendienste und andere Faktoren vergessen. Auch die Firma SeaLines bietet ihren Partnern ein erhöhtes Kapital. Eine der Aktivitäten des Unternehmens ist, dass wir Ihnen eine Untermiete / Leasing / Leasing mit dem Recht anbieten können, einen Container zu kaufen, für den bereits eine Logistikkette etabliert ist, und beladen sie mit einem rentableren Produkt. Du musst deinen Container noch online verfolgen. Wir bieten auch eine bequeme Option für den Kunden zum Rückkauf.</p>
                <br/>
                <p>Wir halten es für unsere Mission, Ihre Zeit zu sparen, Ihr Produkt wettbewerbsfähig zu machen und die Transportkosten zu optimieren. Wir helfen, Fracht von überall in der Welt leicht und schnell zu transportieren, ohne unnötige Mühe und Kosten.<br/>
                Wir haben das Vertrauen unserer Kunden gewonnen, indem wir optimale Lösungen für den Transport von Gütern anbieten und jegliche Fehler im Zusammenhang mit dem menschlichen Faktor eliminieren.<br/>
                Containerschifffahrt auf See ist das Beste, in manchen Fällen sogar die einzige Variante der interkontinentalen Frachtlieferung. Zuverlässig und wirtschaftlich.</p>
                <br/>
                <ul>Vorteile des Seetransports: <br/>
                    <li> - Die niedrigen Kosten der Schifffahrt auf dem Seeweg sind vor allem auf die Möglichkeit der Abholung von Sammelgütern zurückzuführen.</li>
                    <li> - hohe Tragfähigkeit, bei Großgütern wird der Transport von Containern auf dem Seeweg oft nicht nur das Beste, sondern auch die einzig mögliche Liefermöglichkeit.</li>
                    <li> - die Sicherheit der Ladung beim Transport von Containern durch das Meer ist fast nicht vorhanden - das Risiko von Frachtschäden ist minimal. Sea Lines Company ist ein bemerkenswerter Spieler auf dem Containermarkt in Europa, dem Baltikum, Russland und der GUS. Wir spezialisieren uns auf Container der unterschiedlichsten Typen, Abmessungen und Zweck - Trockenfracht oder Universal - Container, Kühlcontainer (Verweigerungen), Tankcontainer, Spezialcontainer usw. Darüber hinaus liefern und stellen wir Hilfsmittel für Container her: Generatorsätze (Aggregate) usw.</li>
                </ul>
                <br/>
                <p>Die SeaLines Company ist seit mehr als 5 Jahren im Containermarkt tätig und das hohe Verständnis der Geschäftsanforderungen der Kunden, die im Laufe der Jahre erreicht wurden, hilft, alle Probleme im Zusammenhang mit der Verwendung von Containern für den multimodalen Transport und die Lagerung schnell und effizient zu lösen von allen Arten von Fracht. Wir bieten unseren Kunden fertige und maßgeschneiderte Lösungen für Transport, Logistik, Bau und sonstige Aktivitäten, in denen Container eingesetzt werden.</p>
                <br/>
                <p>Seit mehr als 5 Jahren bietet SeaLines Company für seine Kunden eine hohe Zuverlässigkeit und Sicherheit des Containerservice. Wir garantieren für die Vertraulichkeit und Sicherheit der Ware während des Transports und der Lagerung (insbesondere im Schutzgebiet neben dem Hafengebiet).</p>
                <br/>',
    'Средиземноморская судоходная компания'=>'Mediterranean Shipping Company',
    'вторая по величине судоходная линия в мире по емкости контейнерных судов.  Как частная компания, он не обязан публиковать ежегодные отчеты, заверенные независимыми сторонами; как следствие, данные MSC-релизы о себе не поддаются проверке. По состоянию на конец декабря 2014 года MSC эксплуатировала 471 контейнерный контейнер с пропускной способностью 2 435 000 единиц эквивалента в двадцать футов (TEU).  Компания Geneva- headquartered  работает во всех крупных портах мира.Наиболее важным портом MSC является Антверпен в Бельгии . MSC Cruises является подразделением компании, ориентированной на праздничные круизы'=>'The second largest shipping line in the world in terms of the capacity of container ships. As a private company, it is not obliged to publish annual reports certified by independent parties; as a consequence, these MSC releases are not verifiable. As of the end of December 2014, MSC operated 471 container containers with a throughput of 2,435,000 equivalent units of twenty feet (TEU). Geneva-headquartered operates in all major ports of the world. The most important port of MSC is Antwerp in Belgium. MSC Cruises is a division of the company, focused on the holiday cruise and marine shipping company',
    'мировой лидер в секторе навалочных грузов, входит в число 10 крупнейших мировых контейнерных операторов и ежегодно перевозит порядка 180 млн тонн груза'=>'the world leader in the bulk cargo sector, is one of the world\'s 10 largest container operators and annually transports about 180 million tons of cargo',
    'была основана 27 апреля 1961 года как первый международный судоходный курьер в Китае, в 1993 году компания превратилась в корпорацию с капиталом в 17 миллиардов долларов.'=>'was founded on April 27, 1961 as the first international shipping courier in China, in 1993 the company turned into a corporation with a capital of 17 billion dollars.',
    'Компания владеет и управляет 800 торговыми судами общим дедвейтом 30 млн тонн.'=>'The company owns and operates 800 commercial vessels with a total deadweight of 30 million tons.',
    'Численность работников — 80 тыс. чел., из которых 5 тыс. — иностранцы.'=>'The number of employees is 80 thousand people, of which 5 thousand are foreigners.',
    'разделена на предприятия специализирующиеся на грузовых перевозках, в т. ч. и контейнеров, и логистических операциях.'=>'is divided into companies specializing in freight transport, including containers and logistics operations.',
    'объединяет 46 дочерних компаний.'=>'unites 46 subsidiaries.',
    'концерн тайваньского конгломерата судоходных и транспортных компаний, и других ассоциированных сервисных компаний.'=>'a concern of the Taiwan conglomerate of shipping and transport companies, and other associated service companies.',
    'Evergreen Group возникла в 1975 году в результате диверсификации бизнеса судоходной компании Evergreen Marine Corporation (EMC), которая была создана в 1968 году, и является, по состоянию на 2013 год, 5-м крупнейшим морским контейнерным перевозчиком в мире.'=>'Evergreen Group originated in 1975 as a result of diversification of the business of the shipping company Evergreen Marine Corporation (EMC), which was established in 1968, and is, as of 2013, the 5th largest container shipping company in the world.',
    'На сегодняшний день Evergreen Group - это около 18 тыс. работников, более 240 офисов/агентств по всему миру, структура из около 50-ти компаний по всему миру, три из которых имеют листинг на Тайбейской фондовой бирже.'=>'To date, the Evergreen Group is about 18,000 employees, more than 240 offices / agencies around the world, a structure of about 50 companies around the world, three of which are listed on the Taipei Stock Exchange.',
    'является французской контейнерной перевозкой и судоходной компанией . Это ведущая мировая судоходная группа , использующая 200 маршрутов доставки от 420 портов в 150 разных странах.  Его штаб-квартира находится в Марселе , а его североамериканская штаб-квартира находится в Норфолке, штат Вирджиния , США.'=>'
is a French container shipping and shipping company. It is the world\'s leading shipping group using 200 delivery routes from 420 ports in 150 different countries. Its headquarter is in Marseilles, and its North American headquarters is in Norfolk, Virginia, USA.',
    'многонациональная немецкая транспортная компания. Он состоит из грузовой контейнерной судоходной линии <span class="strong">Hapag-Lloyd AG</span> , которая, в свою очередь, владеет другими дочерними компаниями, такими как <span class="strong">Hapag-Lloyd Cruises</span> . Грузовое подразделение <span class="strong">Hapag-Lloyd AG</span> в настоящее время является пятым по величине контейнерным перевозчиком в мире по мощности судна .'=>'multinational German transport company. It consists of a cargo container shipping line <span class="strong">Hapag-Lloyd AG</span>, which, in turn, owns other subsidiaries, such as <span class="strong">Hapag-Lloyd Cruises</span>. The cargo division of <span class="strong">Hapag-Lloyd AG</span> is currently the fifth largest container carrier in the world in terms of vessel capacity.',
    'датская компания, оперирующая в различных секторах экономики, по большей части известная портовым и грузовым судоходным бизнесом. Штаб-квартира базируется в Копенгагене, а дочерние предприятия и офисы, в которых занято около 88 тысяч сотрудников, располагаются в более чем 135 странах мира. На 2016 год Maersk является мировым лидером в сфере контейнерных перевозок с долей на рынке более 15 %.'=>'Danish company operating in various sectors of the economy, for the most part known by the port and cargo shipping business. The headquarters is based in Copenhagen, and its subsidiaries and offices, employing about 88,000 employees, are located in more than 135 countries around the world. In 2016, Maersk is the world leader in container transportation with a market share of more than 15%.',
    'зарегистрированный на Бермудах и базирующийся в Гонконге конгломерат с интересами в судоходстве, логистике и недвижимости. Принадлежит очень влиятельной гонконгской семье Тунг (Дун).'=>'registered in Bermuda and a conglomerate based in Hong Kong with interests in shipping, logistics and real estate. It belongs to a very influential Hong Kong family Tung (Dun).'
];