<?php
return [
    'Стандартные контейнеры также называются универсальными контейнерами.'=>'Standard containers are also called universal containers.',
    'Рефрежираторная установка размещена таким образом, чтобы внешние размеры контейнера соответствовали стандартам ISO и установка оптимально помещалась вовнутрь.'=>'The refrigeration unit is placed in such a way that the external dimensions of the container meet ISO standards and the installation is optimally placed inside.',
    'Контейнер имеет отличительную структуру. Крыша состоит из передвижных рам и тента. Дверная перемычка может быть вращающейся.'=>'The container has a distinctive structure. The roof consists of movable frames and awning. The door jumper can be rotating.',
    'Погрузочный поддон состоит из напольного перекрытия с высокой несущей способностью и стального каркаса с настилом из мягкой древесины и двух перегородок'=>'The loading pallet consists of a floor covering with a high bearing capacity and a steel frame with a softwood flooring and two partitions',
    'Такие контейнеры должны быть загружены не менее чем на 80 процентов для предотвращения колебания жидкого груза. С другой стороны, контейнеры не должны заполняться больше чем на 95 процентов, в противном случае возникнет нехватка свободного пространства'=>'Such containers should be loaded at least 80 percent to prevent fluctuations in liquid cargo. On the other hand, containers should not be filled more than 95 percent, otherwise there will be a shortage of free space',
    'Погрузочные поддоны закрыты со всех сторон. Отличия между видами контейнеров:'=>'Loading pallets are closed on all sides. Differences between types of containers:',
    ' • Стандартные контейнеры с дверцами с одной или обеих сторон'=>' • Standard containers with doors on one or both sides',
    ' • Стандартные контейнеры с дверцами на одной или обеих сторонах и дверцами по всей длине'=>' • Standard containers with doors on one or both sides and doors along the entire length',
    ' • Стандартные контейнеры с дверцами на одной или обеих сторонах'=>' • Standard containers with doors on one or both sides',
    'Стандартные контейнеры также отличаются между собой в зависимости от размеров, массы'=>'Standard containers also differ among themselves depending on the size, weight',
    'Как правило используются 20 и 40 футовые контейнеры. Контейнеры меньших размеров используются в редких случаях. Часто используются контейнеры даже больших размеров, например, 45 футов.'=>'Usually 20 and 40 foot containers are used. Smaller containers are used in rare cases. Often used containers are even larger, for example, 45 feet.',
    'Рефрежираторная установка размещена таким образом, чтобы внешние размеры контейнера соответствовали стандартам ISO и установка оптимально помещалась вовнутрь. Наличие рефрижераторной установки приводит к уменьшению внутреннего объема и подвижной нагрузки.'=>'The refrigeration unit is placed in such a way that the external dimensions of the container meet ISO standards and the installation is optimally placed inside. The presence of a refrigerator installation leads to a decrease in the internal volume and the mobile load.',
    'на борту судна груз должен быть подключен к системе электропитания. количество перевозимых рефрижераторных контейнеров зависит от мощности системы электропитания судна. при слабой мощности, могут использоваться силовые агрегаты, которые устанавливаются радом с дизельными генераторами согласно требованиям ISO по размещению 20 футовых контейнеров. на терминале контейнеры подключают к системе электропитания терминала. при транспортировке автомобильным или железнодорожным транспортом, рефрижераторные блоки работают от электрогенераторов, которые в свою очередь могут быть подключены к холодильной установке.'=>'On board the cargo must be connected to the power supply system. The number of refrigerated containers transported depends on the capacity of the ship\'s power supply system. at low power, power units can be used that are installed near diesel generators in accordance with the ISO requirements for the placement of 20-foot containers. At the terminal, the containers are connected to the terminal power supply system. when transported by road or rail, refrigerator units operate from electric generators, which in turn can be connected to a refrigeration unit.',
    'Поток воздуха через контейнер с нижней и верхней частей; теплый воздух поднимается изнутри контейнера, охлаждается в рефрижераторной установке и затем обратно вдувается в контейнер в уже охложденном виде.'=>'Air flow through the container from the bottom and top parts; warm air rises from inside the container, cooled in a refrigerator unit and then back blown into the container in an already chilled form.',
    'Для обеспечения правильной циркуляции охложденного воздуха, на напольном перекрытии встроена решетка. Поддоны образуют дополнительное пространство между напольным пекрытием и грузом, что обеспечивает продув. Кроме того, боковые стенки контейнера гофрированы, что обспечивает необходимый поток воздуха.'=>'To ensure proper circulation of chilled air, a floor grill is built into the floor. The pallets form an additional space between the floor overlap and the load, which ensures a blowing. In addition, the side walls of the container are corrugated, which obpechivaet the necessary air flow.',
    'В верхней части контейнера, должно оставаться пространство (не менее 12 см) для продува. Поэтому, при упаковке контейнера, над грузом необходимо оставить свободное пространство. Максимальная высота загрузки отмечена на боковых стенках.'=>'At the top of the container, there must be a space (at least 12 cm) for blowing. Therefore, when packing the container, leave space above the load. The maximum loading height is marked on the side walls.',
    'Для обеспечения вертикального потока воздуха снизу вверх, конструкция упаковки должна быть соответствующая, и груз размещен правильно'=>'To ensure vertical airflow from the bottom up, the packing design must be appropriate and the load is placed correctly',
    'Регулирование температуры, и наличие интегрального блока, также позволяют контролировать поступление свежего воздуха, например, для выведения метаболических продуктов, таких как СО2 и этилена при перевозке фруктов.'=>'Temperature control, and the presence of an integrated unit, also allow you to monitor the intake of fresh air, for example, for the removal of metabolic products, such as CO2 and ethylene in the transport of fruit.',
    'в холодильных установках измеряется температура поступающего и отработанного воздуха, и в зависимости от рабочего режима данные температуры изпользуются для регулирования потока холодного воздуха. температуру можно измерить разными способами. устройство записи Partlow фиксирует температуру отработанного воздуха, тем самым определяется температурный режим для груза. устройство регистрации данных определяет уровень температуры цифровым способом и выводит данные на дисплей. после передачи данных на компьютер, информация подвергается анализу.'=>'The temperature of the incoming and outgoing air is measured in refrigeration units and, depending on the operating mode, these temperatures are used to control the flow of cold air. the temperature can be measured in many ways. The Partlow recording device records the temperature of the exhaust air, thereby determining the temperature regime for the load. The data logger detects the temperature level digitally and displays the data on the display. after data transfer to the computer, the information is analyzed.',
    'Температурный датчик прикреплен с наружной стороны рефрижераторной установки для контроля за работой установки.'=>'The temperature sensor is attached from the outside of the refrigerator to control the operation of the plant.',
    'Устройства для записи аналоговых и цифровых данных также могут быть размещены непосредственно на грузе для измерения температуры внутри контейнера. Устройсво записи должно быть уставновлено таким образом, чтобы фиксировать критические температуры (внутри упаковки).'=>'Devices for recording analog and digital data can also be placed directly on the cargo to measure the temperature inside the container. The recording device must be set in such a way as to fix the critical temperatures (inside the package).',
    'Встроенные блоки могут быть размещены на верхней и нижней палубах судна. Размещение на верхней палубе имеет свои преимущества, т.к. тепло от воздуха может легко рассеиваться. Однако контейнеры подвержены солнечной радиации, что требует высокой хладопроизводительности холодильных установок.'=>'Built-in units can be placed on the upper and lower decks of the vessel. Accommodation on the upper deck has its advantages, because Heat from the air can easily dissipate. However, containers are exposed to solar radiation, which requires high cooling capacity of refrigeration units.',
    'Показатели'=>'Indicators',
    'Использование'=>'Using',
    'контейнер-рефрижератор используется для перевозки груза, требующего наличия одинаковой температуры как верхней так и нижней точек замерзания. К такому грузу относятся охлаждённые и замороженные продукты, требующие определенной температуры. Это могут быть фрукты, овощи, мясные и молочные продукты, масло и сыр.'=>'The refrigerated container is used to transport cargo that requires the same temperature of both the upper and lower freezing points. This cargo includes refrigerated and frozen foods that require a certain temperature. It can be fruits, vegetables, meat and dairy products, butter and cheese.',
    'Агрегаты с большими объемами используются для объемных и легких грузов (фрукты, цветы)'=>'Aggregates with large volumes are used for bulk and light loads (fruits, flowers)',
    'На сегодняшний день, грузы, требующие заморозки, перевозятся во встроенных агрегатах, которые намного лучше, чем контейнеры с вентиляционными отверстиями.'=>'To date, loads that require freezing are transported in built-in units, which are much better than containers with ventilation holes.',
    'Мясо иногда перевозят в подвешенном состоянии, для этого потолки в контейнерах оборудованы специальными передвижными крюками.'=>'Meat is transported in a suspended state, for this purpose, the ceilings in containers are equipped with special mobile hooks.',
    'Стенки контейнера сделаны из гофрированной стали. Настил деревянный.'=>'The walls of the container are made of corrugated steel. Wooden flooring.',
    'Контейнер имеет отличительную структуру. Крыша состоит из передвижных рам и тента. Дверная перемычка может быть вращающейся.'=>'The container has a distinctive structure. The roof consists of movable frames and awning. The door jumper can be rotating.',
    'Эти две особенности значительно упрощают процесс упаковки и распаковки контейнера. В частности, очень легко упаковать и распаковать контейнер сверху или через двери пр попомщи подъемника или домкрата, если открыта крыша и повернута дверная перемычка'=>'These two features greatly control the process of packaging and unpacking the container. In particular, it is very easy to unpack and unpack the container from above or through the doors, pripamisch lift or jack, if you open the roof and turned the door jumper',
    'Необходимо отметить, что опора крыши в открытом контейнере предназначена для поддержания тента и обеспечить устойчивость контейнера. погрузочный поддон в этом случае • наиболее подходящее средство для высоких грузов.'=>'It should be noted that the roof support in the open container is designed to support the tent and ensure the stability of the container. The loading pallet in this case is the most suitable means for high loads.',
    'Крепежные кольца установлены на верхней и нижней боковых балках и угловых опорах. Кольца могут выдержать груз до 1000 кг.'=>'Fastening rings are installed on the upper and lower side beams and corner supports. Rings can withstand loads of up to 1000 kg.',
    'Стандартные размеры контейнера с открытым верхом 20 и 40 футов.'=>'Standard container sizes with open top • 20 and 40 feet.',
    'Контейнеры с открытым верхом используются для всех видов генеральных грузов (сухой груз). Назначение:'=>'Containers with open top are used for all types of general cargo (dry cargo). Purpose:',
    ' • упаковка и распаковка сверху или через двери при помощи крана или домкрата'=>' • Packing and unpacking from above or through the doors using a crane or a jack',
    ' • для высоких грузов'=>' • for high loads',
    'Погрузочный поддон состоит из напольного перекрытия с высокой несущей способностью и стального каркаса с настилом из мягкой древесины и двух перегородок; поддон может быть закрепленный или разборной. Перегородки защищают груз, при этом несколько поддонов крепятся один на другой. Размеры погрузочного поддона 20 и 40 футов.'=>'The loading pallet consists of a floor covering with a high bearing capacity and a steel frame with a deck of softwood and two partitions; The pallet can be fixed or collapsible. Partitions protect the load, with several pallets attached one to the other. The dimensions of the loading pallet are 20 and 40 feet.',
    'Крепежные кольца, к которым крепится груз, устанавливаются на боковых балках, угловых опорах и полу. Кольца могут выдержать нагрузку до 2000 кг, в случае с 20 футовыми погрузочными поддонами или до 4000 кг с 40 футовыми поддонами.'=>'Fixing rings, to which the load is fixed, are installed on side beams, corner supports and floor. Rings can withstand loads of up to 2,000 kg, in the case of 20-foot loading pallets or up to 4,000 kg with 40-foot pallets.',
    'У некоторых видов 20 футовых контейнеров имеются отверстия для вилочныых погрузчиков.'=>'Some types of 20-foot containers have holes for forklift trucks.',
    '40 футовые поддоны имеют входы s- образной формы с каждой стороны. Иногда на них крепятся крепежная лебедка с 2 тонными крепежными канатами.'=>'40 foot pallets have s-shaped inputs on each side. Sometimes a fastening winch with 2 tons of fastening ropes is attached to them.',
    'для перевозки отдельных видов грузов, погрузочные поддоны могут быть оснащены подпорами.'=>'for the transport of certain types of cargo, loading pallets can be equipped with supports.',
    'Поддоны используются для перевозки тяжелых и крупногабатиных грузов.'=>'Pallets are used for transportation of heavy and large-capacity cargo.',
    'Такие контейнеры должны быть загружены не менее чем на 80 процентов для предотвращения колебания жидкого груза. С другой стороны, контейнеры не должны заполняться больше чем на 95 процентов, в противном случае возникнет нехватка свободного пространства, необходимого для термального расширения, которое может быть рассчитано для каждого груза по формуле:'=>'Such containers should be loaded at least 80 percent to prevent fluctuations in liquid cargo. On the other hand, containers should not be filled more than 95 percent, otherwise there will be a shortage of free space required for thermal expansion, which can be calculated for each cargo according to the formula:',
    'изменение объема'=>'change in volume',
    'объем при начальной температуре'=>'volume at initial temperature',
    'окончательный объем при температуре'=>'the final volume at temperature',
    'коэффициент термального расширения'=>'coefficient of thermal expansion',
    'разница температур в градусах Кельвина'=>'temperature difference in degrees Kelvin',
    'контейнер для жидких грузов, предназначенный для перевозки пищевых продуктов, должен быть маркирован "только для жидких грузов".'=>'A container for liquid cargo intended for the transport of foodstuffs shall be marked "only for liquid cargoes".',
    'Некоторые виды опасных веществ должны перевозиться в контейнерах для жидких грузов с внутренними или внешними отверстиями в нижней части корпуса контейнера.'=>'Some types of hazardous substances should be transported in liquid cargo containers with internal or external holes in the bottom of the container body.',
    'Контейнеры для жидких грузов должны находиться при давлении до 3 бар. испытательное давление составляет 4,5 бар'=>'Containers for liquid cargo must be at a pressure of up to 3 bar. the test pressure is 4.5 bar',
    'если для перевозки груза требуется транспортное средства с регулировкой температурного режима, контейнеры-цистерны могут быть оснащены системами охлаждения или подогрева. температурный режим для груза может быть точно определен при помощи датчиков температуры'=>'if the transport of goods requires a vehicle with temperature control, tank containers can be equipped with cooling or heating systems. The temperature regime for the load can be accurately determined using temperature sensors',
    'Контейнеры для жидкостей используются для перевозки жидких грузов, например:'=>'Containers for liquids are used for the transport of liquid cargo, for example:',
    ' • пищевые продукты: соки, спирт, оливковое масло'=>' • food products: juices, alcohol, olive oil',
    ' • химикаты: опасные вещества, топливо, токсичные вещества, вещества для защиты от коррозии'=>' • chemicals: fear of substance, fuel, toxic substances, corrosion protection substances',
    'организовывает контейнерную перевозку грузов морем в любую точку мира, мы имеем возможность предложить вам выгодные условия доставки и оптимальные для вас маршруты, соединяющие страны и континенты.
                При сотрудничестве с нами вам доступны перевозки из Китая Юго-Восточной Азии, Ближнего Востока, Индии, Африки, Северной Америки, и стран Европы в Россию. Возможна доставка «от двери до двери». Для получения грузов используются прибалтийские и европейские порты и склады.</p>
                <br/>
                <p>Компания SeaLines разрабатывает логистическую цепочку и осуществляет доставку грузов «от двери до двери», начиная с этапа формирования документации и заканчивая выгрузкой контейнера на вашем складе.</p>
                <br/>
                <p>Наша компания предоставляет большой перечень услуг. Став нашим партнером, у Вас появятся возможности, которые другие компании Вам не смогут предоставить. С нашей помощью Вы сможете: доставить свой груз, забыть про оформление документации, про портовые услуги и прочие факторы. Так же, компания SeaLines предлагает своим партнерам приумножить свой капитал. Один из видов деятельности компании заключается в том, что Мы Вам можем предложить взять в субаренду\аренду\аренду с правом выкупа контейнера, для которых уже налажена логистическая цепочка, загрузка его более рентабельным товаром. Вам остается отслеживать онлайн свой контейнер. Также мы предоставляем удобную для клиента опцию выкупа контейнеров (buy-back).</p>
                <br/>
                <p>Мы считаем своей миссией сохранить ваше время, сделать ваш продукт конкурентным и оптимизировать транспортные расходы. Мы помогаем перевезти груз из любой точки мира легко и быстро, без лишних хлопот и затрат.<br/>
                Мы завоевали доверие наших клиентов тем, что предложили оптимальные решения по перевозке грузов и исключили любые ошибки, связанные с человеческим фактором.<br/>
                Контейнерные перевозки морем — лучший, в некоторых случаях даже единственный вариант межконтинентальной доставки грузов. Надежно и экономично.</p>
                <br/>
                <ul>Преимущества перевозок по-морю:<br/>
                    <li> - низкая стоимость доставки морем во многом объясняется возможностью комплектации сборных грузов.</li>
                    <li> - высокая грузоподъемность, в случае с крупногабаритными грузами, перевозка контейнеров морем зачастую становится не только лучшим, но и единственно возможным вариантом доставки.</li>
                    <li> - сохранность груза при транспортировке контейнеров морем практически отсутствуют — риск повреждения грузов минимальный.
                    Sea Lines Company  является заметным игроком на контейнерном рынке в Европе, Балтии, России и СНГ. Мы специализируемся на контейнерах самого широкого спектра типов, габаритов и целевого назначения - сухогрузные или универсальные (морские) контейнеры, рефрижераторные контейнеры (реферы), танк-контейнеры, специализированные контейнеры и т.д. Помимо этого мы поставляем и налаживаем вспомогательное оборудование для контейнеров: генераторные установки (дженсеты) и т.д.</li>
                </ul>
                <br/>
                <p>SeaLines Company работает на контейнерном рынке более 5 лет, и достигнутый за годы работы высокий уровень понимания бизнес-потребностей клиентов помогает быстро и эффективно решать все вопросы, связанные с использованием контейнеров для мультимодальных перевозок и складирования всех видов грузов. Мы обеспечиваем клиентам готовые и индивидуальные решения в транспортировке, логистике, строительстве и любых других видах деятельности, где находится применение контейнерам.</p>
                <br/>
                <p>Уже более 5ти лет SeaLines Company обеспечивает высокую надежность и безопасность контейнерного сервиса для своих клиентов. Мы ручаемся за конфиденциальность и сохранность грузов при перевозке и хранении (в частности, на охраняемой территории, прилегающей к портовой зоне).</p>
                <br/>'=>'organizes container transportation of cargo by sea to anywhere in the world, we have the opportunity to offer you favorable terms of delivery and optimal routes for you connecting countries and continents.
                In cooperation with us, you can get transportation from China to Southeast Asia, the Middle East, India, Africa, North America, and Europe to Russia. Delivery is possible "from door to door". To receive cargo, Baltic and European ports and warehouses are used. </ P>
                <br/>
                <p> SeaLines develops a logistics chain and delivers goods "from door to door" starting from the stage of documentation formation and ending with the unloading of the container in your warehouse. </ p>
                <br/>
                <p> Our company provides a wide range of services. Becoming our partner, you will have opportunities that other companies will not be able to provide to you. With our help, you can: deliver your cargo, forget about the design of documentation, about port services and other factors. Also, the company SeaLines offers its partners to increase their capital. One of the activities of the company is that we can offer you a sublease / lease / lease with the right to purchase a container for which a logistics chain has already been established, loading it with a more profitable product. You still have to track your container online. We also provide a convenient option for the customer to buy-back. </ P>
                <br/>
                <p> We consider it our mission to save your time, make your product competitive and optimize transportation costs. We help to transport cargo from anywhere in the world easily and quickly, without any unnecessary hassle and expense. <br/>
                We have won the trust of our customers by offering optimal solutions for the transportation of goods and eliminating any errors related to the human factor. <br/>
                Container shipping by sea is the best, in some cases even the only variant of intercontinental cargo delivery. Reliable and economical. </ P>
                <br/>
                <ul> Advantages of sea transportation: <br/>
                    <li> - The low cost of shipping by sea is largely due to the possibility of picking up groupage cargoes. </ li>
                    <li> - high carrying capacity, in the case of large-sized cargoes, the transportation of containers by sea often becomes not only the best, but also the only possible option for delivery. </ li>
                    <li> - the safety of the cargo during the transportation of containers by the sea is almost non-existent - the risk of cargo damage is minimal.
                    Sea Lines Company is a notable player in the container market in Europe, the Baltics, Russia and the CIS. We specialize in containers of the widest range of types, dimensions and purpose - dry cargo or universal (sea) containers, refrigerated containers (referrals), tank containers, specialized containers, etc. In addition, we supply and establish auxiliary equipment for containers: generator sets (gensets), etc. </ li>
                </ ul>
                <br/>
                <p> SeaLines Company has been operating in the container market for more than 5 years, and the high level of understanding of the business needs of customers achieved over the years helps to quickly and efficiently solve all issues related to the use of containers for multimodal transport and warehousing of all types of cargo. We provide our clients with ready-made and customized solutions for transportation, logistics, construction and any other activities where containers are used. </ P>
                <br/>
                <p> For more than 5 years SeaLines Company has been providing high reliability and security of container service for its customers. We vouch for the confidentiality and safety of the goods during transportation and storage (in particular, in the protected area adjacent to the port area). </ P>
                <br/>',
    'Средиземноморская судоходная компания'=>'Mediterranean Shipping Company',
    'вторая по величине судоходная линия в мире по емкости контейнерных судов.  Как частная компания, он не обязан публиковать ежегодные отчеты, заверенные независимыми сторонами; как следствие, данные MSC-релизы о себе не поддаются проверке. По состоянию на конец декабря 2014 года MSC эксплуатировала 471 контейнерный контейнер с пропускной способностью 2 435 000 единиц эквивалента в двадцать футов (TEU).  Компания Geneva- headquartered  работает во всех крупных портах мира.Наиболее важным портом MSC является Антверпен в Бельгии . MSC Cruises является подразделением компании, ориентированной на праздничные круизы'=>'The second largest shipping line in the world in terms of the capacity of container ships. As a private company, it is not obliged to publish annual reports certified by independent parties; as a consequence, these MSC releases are not verifiable. As of the end of December 2014, MSC operated 471 container containers with a throughput of 2,435,000 equivalent units of twenty feet (TEU). Geneva-headquartered operates in all major ports of the world. The most important port of MSC is Antwerp in Belgium. MSC Cruises is a division of the company, focused on the holiday cruise and marine shipping company',
    'мировой лидер в секторе навалочных грузов, входит в число 10 крупнейших мировых контейнерных операторов и ежегодно перевозит порядка 180 млн тонн груза'=>'the world leader in the bulk cargo sector, is one of the world\'s 10 largest container operators and annually transports about 180 million tons of cargo',
    'была основана 27 апреля 1961 года как первый международный судоходный курьер в Китае, в 1993 году компания превратилась в корпорацию с капиталом в 17 миллиардов долларов.'=>'was founded on April 27, 1961 as the first international shipping courier in China, in 1993 the company turned into a corporation with a capital of 17 billion dollars.',
    'Компания владеет и управляет 800 торговыми судами общим дедвейтом 30 млн тонн.'=>'The company owns and operates 800 commercial vessels with a total deadweight of 30 million tons.',
    'Численность работников — 80 тыс. чел., из которых 5 тыс. — иностранцы.'=>'The number of employees is 80 thousand people, of which 5 thousand are foreigners.',
    'разделена на предприятия специализирующиеся на грузовых перевозках, в т. ч. и контейнеров, и логистических операциях.'=>'is divided into companies specializing in freight transport, including containers and logistics operations.',
    'объединяет 46 дочерних компаний.'=>'unites 46 subsidiaries.',
    'концерн тайваньского конгломерата судоходных и транспортных компаний, и других ассоциированных сервисных компаний.'=>'a concern of the Taiwan conglomerate of shipping and transport companies, and other associated service companies.',
    'Evergreen Group возникла в 1975 году в результате диверсификации бизнеса судоходной компании Evergreen Marine Corporation (EMC), которая была создана в 1968 году, и является, по состоянию на 2013 год, 5-м крупнейшим морским контейнерным перевозчиком в мире.'=>'Evergreen Group originated in 1975 as a result of diversification of the business of the shipping company Evergreen Marine Corporation (EMC), which was established in 1968, and is, as of 2013, the 5th largest container shipping company in the world.',
    'На сегодняшний день Evergreen Group - это около 18 тыс. работников, более 240 офисов/агентств по всему миру, структура из около 50-ти компаний по всему миру, три из которых имеют листинг на Тайбейской фондовой бирже.'=>'To date, the Evergreen Group is about 18,000 employees, more than 240 offices / agencies around the world, a structure of about 50 companies around the world, three of which are listed on the Taipei Stock Exchange.',
    'является французской контейнерной перевозкой и судоходной компанией . Это ведущая мировая судоходная группа , использующая 200 маршрутов доставки от 420 портов в 150 разных странах.  Его штаб-квартира находится в Марселе , а его североамериканская штаб-квартира находится в Норфолке, штат Вирджиния , США.'=>'
is a French container shipping and shipping company. It is the world\'s leading shipping group using 200 delivery routes from 420 ports in 150 different countries. Its headquarter is in Marseilles, and its North American headquarters is in Norfolk, Virginia, USA.',
    'многонациональная немецкая транспортная компания. Он состоит из грузовой контейнерной судоходной линии <span class="strong">Hapag-Lloyd AG</span> , которая, в свою очередь, владеет другими дочерними компаниями, такими как <span class="strong">Hapag-Lloyd Cruises</span> . Грузовое подразделение <span class="strong">Hapag-Lloyd AG</span> в настоящее время является пятым по величине контейнерным перевозчиком в мире по мощности судна .'=>'multinational German transport company. It consists of a cargo container shipping line <span class="strong">Hapag-Lloyd AG</span>, which, in turn, owns other subsidiaries, such as <span class="strong">Hapag-Lloyd Cruises</span>. The cargo division of <span class="strong">Hapag-Lloyd AG</span> is currently the fifth largest container carrier in the world in terms of vessel capacity.',
    'датская компания, оперирующая в различных секторах экономики, по большей части известная портовым и грузовым судоходным бизнесом. Штаб-квартира базируется в Копенгагене, а дочерние предприятия и офисы, в которых занято около 88 тысяч сотрудников, располагаются в более чем 135 странах мира. На 2016 год Maersk является мировым лидером в сфере контейнерных перевозок с долей на рынке более 15 %.'=>'Danish company operating in various sectors of the economy, for the most part known by the port and cargo shipping business. The headquarters is based in Copenhagen, and its subsidiaries and offices, employing about 88,000 employees, are located in more than 135 countries around the world. In 2016, Maersk is the world leader in container transportation with a market share of more than 15%.',
    'зарегистрированный на Бермудах и базирующийся в Гонконге конгломерат с интересами в судоходстве, логистике и недвижимости. Принадлежит очень влиятельной гонконгской семье Тунг (Дун).'=>'registered in Bermuda and a conglomerate based in Hong Kong with interests in shipping, logistics and real estate. It belongs to a very influential Hong Kong family Tung (Dun).'
];